[camera]
hsize = 500
vsize = 250
fov_as_degrees = 90
from = [0.0, 1.5, -5.0]
to = [0.0, 1.0, 0.0]
up = [0.0, 1.0, 0.0]

[[world.lights]]
position = [-10.0, 10.0, -10.0]
intensity = [1.0, 1.0, 1.0]

# floor
[[world.objects]]
    shape = "Plane"
    transforms = [
        { Scale = {x = 10.0, y = 0.01, z = 10.0} },
        { Translate = {x = 0.0, y = -1.0, z = 0.0} }
    ]
    [world.objects.material]
        colour = [1.0, 0.9, 0.9]
        specular = 0.0


# left
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Scale = { x = 0.33, y = 0.33, z = 0.33} },
        { Translate = { x = -1.5, y = 0.33, z = -0.75} }
    ]
    [world.objects.material]
        colour = [0.5, 1.0, 0.1]
        diffuse = 0.7
        specular = 0.3

# middle
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Translate = { x = -0.5, y = 1.0, z = 0.5} }
    ]
    [world.objects.material]
        colour = [0.1, 1.0, 0.5]
        diffuse = 0.7
        specular = 0.3

# right
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Scale = { x = 0.5, y = 0.5, z = 0.5} },
        { Translate = { x = 1.5, y = 0.5, z = -0.5} }
    ]
    [world.objects.material]
        colour = [0.5, 1.0, 0.1]
        diffuse = 0.7
        specular = 0.3
