[camera]
hsize = 2560
vsize = 1600
fov_as_degrees = 60
from = [0.0, 1.5, -5.0]
to = [0.0, 1.0, 0.0]
up = [0.0, 1.0, 0.0]

[[world.lights]]
position = [-10.0, 10.0, -10.0]
intensity = [1.0, 1.0, 1.0]

# floor
[[world.objects]]
    shape = "Sphere"
    transforms = [ { Scale = {x = 10.0, y = 0.01, z = 10.0} } ]
    [world.objects.material]
        colour = [1.0, 0.9, 0.9]
        specular = 0.0

# right wall
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Scale = {x = 10.0, y = 0.01, z = 10.0} },
        { RotateX = {angle = 90.0} },
        { RotateY = {angle = 45.0} },
        { Translate = {x = 0.0, y = 0.0, z = 5.0} }
    ]
    [world.objects.material]
        colour = [1.0, 0.9, 0.9]
        specular = 0.0

# left wall
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Scale = {x = 10.0, y = 0.01, z = 10.0} },
        { RotateX = {angle = 90.0} },
        { RotateY = {angle = -45.0} },
        { Translate = {x = 0.0, y = 0.0, z = 5.0} }
    ]

    [world.objects.material]
        colour = [1.0, 0.9, 0.9]
        specular = 0.0

# left
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Scale = { x = 0.33, y = 0.33, z = 0.33} },
        { Translate = { x = -1.5, y = 0.33, z = -0.75} }
    ]
    [world.objects.material]
        pattern = { Gradient = { from = [1.0, 0.0, 0.0], to = [1.0, 1.0, 0.0] } }
        pattern_to_object_spc = [
            { Translate = [-0.5, 0.0, 0.0] },
            { Scale = {x = 2.0, y = 2.0, z = 2.0} },
            { RotateZ = {angle = 60.0}}
        ]
        diffuse = 0.7
        specular = 0.3

# middle
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Translate = { x = -0.5, y = 1.0, z = 0.5} }
    ]
    [world.objects.material]
        pattern = { Stripes = { a = [0.1, 1.0, 0.5], b = [1.0, 1.0, 1.0] } }
        pattern_to_object_spc = [
            { Translate = [0.5, 0.0, 0.0] },
            { RotateZ = {angle = 60.0}}
        ]
        diffuse = 0.7
        specular = 0.3

# right
[[world.objects]]
    shape = "Sphere"
    transforms = [
        { Scale = { x = 0.5, y = 0.5, z = 0.5} },
        { Translate = { x = 1.5, y = 0.5, z = -0.5} }
    ]
    [world.objects.material]
        pattern = { Checkers = { a = [0.0, 0.75, 1.0], b = [0.0, 0.0, 1.0] }}
        pattern_to_object_spc = [
            { Scale = { x = 0.2, y = 0.2, z = 0.2 } },
            { RotateZ = { angle = 60.0 } },
            { RotateY = { angle = -60.0 } }
        ]
        diffuse = 0.7
        specular = 0.3

